<style>
    .rd-parallax-inner {
        min-height: 200px;
    }
    .parallax-1 {
        margin-left: calc(50% - 50vw);
        margin-right: calc(50% - 50vw);
    }
</style>

<div class="menu-for-mobile">
        <div class="text-layout">
            <div class="parallax-text2"><a href="http://pulcinella.ro/pizza.html">Pizza</a></div>
            <div class="parallax-text2"><a href="http://pulcinella.ro/insalata.html">Insalata</a></div>
            <div class="parallax-text2"><a href="http://pulcinella.ro/dolci.html">Dolci</a></div>
            <div class="parallax-text2"><a href="http://pulcinella.ro/bar.html">Bar</a></div>
        </div>
</div>