<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('Daca este vorba despre pizza noastra, atunci trebuie sa ne contactatezi neaparat!') ?></div>
        <div class="row">
            <div class="field name required col-sm-4">
                <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Nume si Prenume') ?></span></label>
                <div class="control">
                    <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Nume si Prenume') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required col-sm-4">
                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field telephone col-sm-4">
                <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Numar de Telefon') ?></span></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Numar de Telefon') ?>" value="" class="input-text" type="text" />
                </div>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Mesajul tau') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Mesajul tau') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Trimite') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Trimite') ?></span>
            </button>
        </div>
    </div>
</form>
