<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br>
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getNameBlockHtml() ?>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend><br>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

        <div class="field city required">
            <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('Localitate') ?></span></label>
            <div class="control">
                <select id="city" name="city" title="<?php /* @escapeNotVerified */ echo __('Localitate') ?>" class="validate-select";?>>
                    <option <?php echo ($block->getAddress()->getCity() == 'Timișoara')?'selected':'' ?> value="<?php /* @escapeNotVerified */ echo __('Timișoara') ?>"><?php /* @escapeNotVerified */ echo __('Timișoara') ?></option>
                    <option <?php echo ($block->getAddress()->getCity() == 'Săcălaz')?'selected':'' ?> value="<?php /* @escapeNotVerified */ echo __('Săcălaz') ?>"><?php /* @escapeNotVerified */ echo __('Săcălaz') ?></option>
                    <option <?php echo ($block->getAddress()->getCity() == 'Dumbrăvița')?'selected':'' ?> value="<?php /* @escapeNotVerified */ echo __('Dumbrăvița') ?>"><?php /* @escapeNotVerified */ echo __('Dumbrăvița') ?></option>
                    <option <?php echo ($block->getAddress()->getCity() == 'Ghiroda')?'selected':'' ?> value="<?php /* @escapeNotVerified */ echo __('Ghiroda') ?>"><?php /* @escapeNotVerified */ echo __('Ghiroda') ?></option>
                    <option <?php echo ($block->getAddress()->getCity() == 'Giroc')?'selected':'' ?> value="<?php /* @escapeNotVerified */ echo __('Giroc') ?>"><?php /* @escapeNotVerified */ echo __('Giroc') ?></option>
                </select>
            </div>
        </div>
        <div class="field street required">
            <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
                </div>
            </div>
        <?php endif; ?>

        <input type="hidden" id="region_id" name="region_id" value="315"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
        <input type="hidden" id="region" name="region" value="Timis"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>

        <input type="hidden" id="country_id" name="country_id" value="RO"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>

        <input type="hidden" id="lat" name="lat" value="<?php if (!empty($block->getAddress()->getCustomAttribute("lat"))) { echo $block->getAddress()->getCustomAttribute("lat")->getValue(); } ?>"  title="<?php /* @escapeNotVerified */ echo __('Latitude') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
        <input type="hidden" id="lon" name="lon" value="<?php if (!empty($block->getAddress()->getCustomAttribute("lon"))) { echo $block->getAddress()->getCustomAttribute("lon")->getValue(); } ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
        <div id="map"></div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <input type="hidden" id="primary_shipping" name="default_shipping" value="0">
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>

<script>
    require(
        [
            'jquery'
        ],
        function(
            $
        ) {
            $("#primary_billing").click( function(){
                if( $(this).is(':checked') ) {
                    $("#primary_shipping").val(1);
                } else {
                    $("#primary_shipping").val(0);
                };
            });

        }
    );
</script>

<script type="text/javascript">
    require([
        'jquery',
        'googleMapPagePlugin'
    ], function($){

        var marker = false;
        var map;

        //The center location of our map.
        var centerOfMap = new google.maps.LatLng(45.7541614,21.2324269);

        //Map options.
        var options = {
            center: centerOfMap, //Set center.
            zoom: 13 //The zoom value.
        };

        //Create the map object.
        map = new google.maps.Map(document.getElementById('map'), options);

        var lat = $('#lat').val();
        var lon = $('#lon').val();
        if(lat != '' && lon != '' ){
            marker = new google.maps.Marker({
                position: new google.maps.LatLng(lat,lon),
                map: map,
                draggable: true //make it draggable
            });
        } else {
            marker = new google.maps.Marker({
                position: centerOfMap,
                map: map,
                draggable: true //make it draggable
            });

            document.getElementById('lat').value = centerOfMap.lat(); //latitude
            document.getElementById('lon').value = centerOfMap.lng();
        }

        //Listen for any clicks on the map.
        google.maps.event.addListener(map, 'click', function(event) {
            //Get the location that the user clicked.
            var clickedLocation = event.latLng;
            //If the marker hasn't been added.
            if(marker === false){
                //Create the marker.
                marker = new google.maps.Marker({
                    position: clickedLocation,
                    map: map,
                    draggable: true //make it draggable
                });
                //Listen for drag events!
                google.maps.event.addListener(marker, 'dragend', function(event){
                    markerLocation();
                });
            } else{
                //Marker has already been added, so just change its location.
                marker.setPosition(clickedLocation);
            }
            //Get the marker's location.
            markerLocation();
        });

        function markerLocation(){
            //Get location.
            var currentLocation = marker.getPosition();
            var geocoder = new google.maps.Geocoder;

            //Add lat and lng values to a field that we can save.
            document.getElementById('lat').value = currentLocation.lat(); //latitude
            document.getElementById('lon').value = currentLocation.lng(); //longitude

            var markerLoc = new google.maps.LatLng(currentLocation.lat(),currentLocation.lng());
            geocoder.geocode({'location': markerLoc}, function(results, status) {
                if (status === 'OK') {
                    if (results[0]) {
                        var addressArray = (results[0].formatted_address).split(',');
                        var city = (addressArray[1].trim()).split(' ', 2);
                        if(SelectHasValue('city', city[0])){
                            document.getElementById('city').value = city[0];
                            document.getElementById('street_1').value = addressArray[0];
                        } else {
                            document.getElementById('city').value = '';
                            document.getElementById('street_1').value = '';
                            document.getElementById('street_2').value = '';
                            window.alert('Adresa nu se afla in zona de livrare');
                        }
                    } else {
                        window.alert('No results found');
                    }
                } else {
                    window.alert('Geocoder failed due to: ' + status);
                }
            });
        }
    });

    function SelectHasValue(select, value) {
        obj = document.getElementById(select);

        if (obj !== null) {
            return (obj.innerHTML.indexOf('value="' + value + '"') > -1);
        } else {
            return false;
        }
    }

</script>


<style type="text/css">
    #map{ width:100%; height: 500px; }
</style>
