<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Partea cea mai grea a trecut, iar comanda %1 e pe maini bune. Pune la rece berea sau sucul si verifica-ti email-ul pentru detaliile de livrare.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Partea cea mai grea a trecut, iar comanda <span>%1</span> e pe maini bune. Pune la rece berea sau sucul si verifica-ti email-ul pentru detaliile de livrare.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
    <?php endif;?>
    <div>
        <p>Daca ai optat pentru ridicare personala, te asteptam in maximum 30 de minute. Da, cam atat de repede ne miscam 😃</p>
    </div>
    <div>
        <p>Iti multumim ca ai ales cea mai italiana italiana italiana pizza din oras!</p>
    </div>
    <p>
        <p>Pulcinella</p>
    </div>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar actions-toolbar-success">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
