<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();

$product = $_item->getProduct();
$additionalData = $_item->getAdditionalData();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$options = array();
if($additionalData) {
    $productsArray = unserialize($additionalData);
    foreach ($productsArray as $key => $value) {
        $productId = $value;
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $productObject = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
        $options[] = array(
            'name' => $productObject->getName(),
            'price' => (int)$productObject->getPrice() . " RON"
        );
    }
}
?>
<?php if($product->getAttributeSetId() != 10): ?>
    <tr>
        <td class="item-info<?php if (!empty($options)): ?> has-extra<?php endif; ?>">
            <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
            <?php if (!empty($options)): ?>
                <dl class="item-options">
                    <?php foreach ($options as $option): ?>
                        <dt><strong><em><?= /* @escapeNotVerified */  $option['name'] ?></em></strong></dt>
                        <dd>
                            <?= /* @escapeNotVerified */  nl2br($option['price']) ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td class="item-price">
            <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
        </td>
    </tr>
<?php endif; ?>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
