<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
<!--    <legend class="legend"><span>--><?php ///* @escapeNotVerified */ echo __('Additional Information') ?><!--</span></legend>-->
    <p>
    <div class="field required">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Telephone') ?></span></label>
        <div class="control">
            <input type="text" name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
</fieldset>